alias vim='vim -O'
alias ghash='openssl rand -base64 48'
alias nocors='google-chrome --disable-web-security --user-data-dir'
alias tor='~/tor-browser_en-US/Browser/start-tor-browser'
alias sudo='sudo '
alias keepassxc='firejail --net=none --appimage ~/KeePassXC-<version>-x86_64.AppImage'
alias charles='~/charles/bin/charles'
alias firefox='firejail firefox &'
alias virtualbox="firejail --noprofile virtualbox &"
alias nomonitors='xrandr --output HDMI-1-0 --off'
alias actmonitors='xrandr --output HDMI-1-0 --auto --right-of eDP-1'
