alias vim='vim -O'
alias ghash='openssl rand -base64 48'
alias nocors='google-chrome --disable-web-security --user-data-dir'
alias loports='ss -antup; netstat -antup; lsof -i'
alias tor='~/tor-browser_en-US/Browser/start-tor-browser'
alias sudo='sudo '
alias keepassxc='firejail --net=none --appimage ~/KeePassXC-<version>-x86_64.AppImage'
alias suidfiles='find / -perm -u=s -type f 2>/dev/null'
alias charles='~/charles/bin/charles'
